"""empty message

Revision ID: 50adf66055c8
Revises: 7d79d1189bf6
Create Date: 2019-12-14 21:50:00.324819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50adf66055c8'
down_revision = '7d79d1189bf6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
