"""empty message

Revision ID: ecc0dfdb7191
Revises: 203357ce2e35
Create Date: 2019-12-14 23:42:18.320236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecc0dfdb7191'
down_revision = '203357ce2e35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('notes', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'notes')
    # ### end Alembic commands ###
